# Generated by Django 3.2.5 on 2021-10-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('contents', models.CharField(max_length=10000)),
                ('created_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='target',
            name='health',
        ),
    ]
