# Generated by Django 3.2.5 on 2021-10-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211003_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='domain',
            new_name='host',
        ),
        migrations.AlterField(
            model_name='target',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
